### PR TITLE
one more thing

### PR DESCRIPTION
**Pull request by hoodie**
sorry, I had some left overs I forgot to commit

### CODE REVIEW

**Comment by badboy** [comment]
You're really not liking the rustfmt on the tests, do you? :D

**Comment by hoodie** [comment]
that was not it, but ... yes
these are repetitive lines that change in small places, you can spot the differences more quickly when they are aligned like tables.
that map! instead of chain! was your idea though :grinning:

**Comment by badboy** [comment]
We still need those features though, otherwise a build on !nightly fails.
I'm gonna cherry-pick this.

**Comment by badboy** [comment]
Oh, we need to keep clippy as a dependency currently as we can't use features for dev-deps

**Comment by hoodie** [comment]
ups, why did github allow me to update your comment?
I'm updating my nightly right now ... still building, weird

**Comment by badboy** [comment]
Haha :D Because you're now a collaborator on this repository.

**Comment by hoodie** [comment]
ohh, thanks for that, didn't read my email of late

**Pull request closed without merging**
