### PR TITLE
fixed: opt! behaviour change in nom 1.0.0 final

### PR DESCRIPTION
**Pull request by hoodie**
hey, nom changed  something [last minute](https://github.com/Geal/nom/commit/79080d5f7a9d1da49cff5a2baef889f5d1e227a3) before releasing v1.0.0 which broke pretty much overything :open_mouth: 
this fixes it again

### CODE REVIEW

**Comment by badboy** [comment]
Can you update clippy while you're at it?

**Comment by badboy** [comment]
Maybe we could just use `~0.0.23` for the clippy dependency, then we get a few more updates before something really breaks.

**Comment by badboy** [comment]
@homu r+

**Comment by hoodie** [comment]
ok, could you publish that version ? thanks

**Comment by badboy** [comment]
I'll do.

**Pull request merged**
