### PR TITLE
Add construction methods to the duration enum

### PR DESCRIPTION
**Pull request by HenningCode**
Hello @hoodie,

 I just created some constructor methods and methods to chain the operations, but its not that elegant, because I had to return a result. Do you have a better idea or would you just remove them again?

### CODE REVIEW

**Comment by hoodie** [comment]
You can probably introduce an intermediate type and only convert to the `Duration` at the very end. This is something that you find in a bunch of builder pattern implementations.

**Comment by HenningCode** [comment]
@hoodie Do you maybe have an example of that? I am a bit new to Rust and havent worked a lot with enum variants.

**Comment by hoodie** [comment]
Take a look [here](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html). Maybe like this
```rs
impl Duration {
  fn build() -> DurationBuilder {}
}
```

and then that `DurationBuilder` only has the methods and it contains a prototype of the `Duration`, could even be `Duration` itself. You could make `DurationBuilder::weeks()` return the `Duration`, that would finalize the build.

**Comment by HenningCode** [comment]
Ok I understood that now and how it would be implemented in Rust, but thats quite hard / impossible to realize with an enum variant I think. 

If you think about this function which would be part of the Durationbuilder: `fn year(&mut self, year: u32) -> &mut self` Its not possible to return a `&mut self` because you would have to match self and extract and reconstruct a new Durationbuilder. Also there is nothing that stops you from calling `.year(2)` on the `Weeks` variant type. One solution would be to create two seperate structs for `Weeks` and `YMDHMS`, which would require a big rewrite..

**Pull request closed without merging**
