### PR TITLE
update to nom 4

### PR DESCRIPTION
**Pull request by Geal**
Hello,

I'm currently testing the upgrade to nom 4 on various crates, to see if I forgot anything. Currently, I get this error after doing the following changes:

```

failures:

---- test_time_with_timezone stdout ----
        thread 'test_time_with_timezone' panicked at 'assertion failed: `(left == right)`
  left: `Ok((CompleteByteSlice([43, 48, 53, 58]), Time { hour: 16, minute: 43, second: 16, millisecond: 0, tz_offset_hours: 0, tz_offset_minutes: 0 }))`,
 right: `Ok((CompleteByteSlice([58]), Time { hour: 16, minute: 43, second: 16, millisecond: 0, tz_offset_hours: 5, tz_offset_minutes: 0 }))`', tests/lib.rs:161:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    test_time_with_timezone

test result: FAILED. 24 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

The most notable change is the introduction of the `CompleteByteSlice` type, which removes all `Incomplete` usage, assuming the input is complete. See [the upgrade doc](https://github.com/Geal/nom/blob/master/doc/upgrading_to_nom_4.md#dealing-with-incomplete-usage) for more information.

### CODE REVIEW

**Comment by sylvestre** [comment]
@Geal @ignatenkobrain in the context of packaging exa in Debian, it would make our life easier to have this packaging using nom 4. Is that something you could do? Thanks

**Comment by badboy** [comment]
exa is using this? Wuih, I didn't know. I'm happy to merge nom 4 support and take on new maintainers, as I personally don't have much time to properly maintain it.

**Comment by ignatenkobrain** [comment]
FYI, in Fedora we just ship nom3 and do not care.

**Comment by hoodie** [comment]
of course exa is using it :smile:  I basically pushed this for exa :grin:

**Comment by sylvestre** [comment]
@badboy could you please share an update on this? we are trying to get exa in Debian & Ubuntu and we would prefer to use nom v4. Thanks

**Comment by badboy** [comment]
What I said before stands. I don't have the time to maintain it. If you require it to work on nom v4 I'd be happy to merge support for it, but at least this PR is currently leading to test errors. 
If you submit a new one, I can spend some time on review and then also give you commit permission on this repository.

**Comment by infinity0** [comment]
If this doesn't work with nom-4 we are unlikely to be able to get exa into Debian Testing (freeze in Jan) because nom-3 has a whole dependency tree that we haven't yet packaged, which would be necessary for it to go in Debian Testing.

**Comment by Geal** [comment]
There's probably not much to do to fix that PR, but like @badboy I don't have time to spare for this.
@infinity0 can someone from exa look into it?

**Comment by badboy** [comment]
I'm fine with adjusting tests if needed.
I never really decided whether it should always parse the full line and thus fail with trailing stuff or just ignore that and let the user handle it.

We should at least document the behaviour.

**Comment by kpcyrd** [comment]
Awesome, I've submitted my patch as #21

**Pull request closed without merging**
